project:
  type: website
  output-dir: docs

website:
  title: "Welcome"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About 
      - href: https://static-bcrf.biochem.wisc.edu/courses/Tabular-data-analysis-with-R-and-Tidyverse/book/5-workingwithtabulardata.html
        text: For More Information 

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

