project:
  type: website
  output-dir: docs

website:
  title: "Welcome"
  navbar:
    left:
      - href: about.qmd
        text: About
      - href: https://github.com/eexvqn/Previous-Work
        text: Link to Folders
        
format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

