project:
  type: website
  output-dir: docs

website:
  title: "Environment"
  navbar:
    left:
      - href: index.qmd
        text: General
      - href: AppLink.qmd
        text: Analysis
      - href: about.qmd
        text: Author
      - href: https://github.com/eexvqn/Previous-Work
        text: Link to Folders
        
format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

